networked: tamidsh_networked.c sockutils.c
	gcc -o tamidsh_networked tamidsh_networked.c sockutils.c

dumbfetch: dumbfetch.c sockutils.c
	gcc -o dumbfetch dumbfetch.c sockutils.c

clean:
	rm dumbfetch dumbfetch2 tamidsh_networked

