
all: files files2 tamidcat

files: files.c
	gcc -o files files.c

files2: files2.c
	gcc -o files2 files2.c

tamidcat: tamidcat.c
	gcc -o tamidcat tamidcat.c

remove:
	rm files files2 tamidcat out.txt