tamidsh_part1: tamidsh_part1.c
	gcc -o tamidsh_part1 tamidsh_part1.c

networked: tamidsh_networked.c sockutils.c
	gcc -o tamidsh_networked tamidsh_networked.c sockutils.c

dumbfetch: dumbfetch.c sockutils.c
	gcc -o dumbfetch dumbfetch.c sockutils.c

dumbfetch2: dumbfetch2.c sockutils.c
	gcc -o dumbfetch2 dumbfetch2.c sockutils.c

clean:
	rm dumbfetch dumbfetch2
